# Project information
site_name: 'TTT2 Documentation'
site_description: "A Garry's Mod gamemode based on Trouble in Terrorist Town"
#site_url: 'https://'

# Repository
repo_name: 'TTT2'
repo_url: https://github.com/TTT-2/TTT2/
edit_uri: https://github.com/TTT-2/docs/edit/master/docs/

# Configuration
theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Navigation
nav:
  - General: 
    - TTT2: 'index.md'
    - Troubleshooting: 'troubleshooting/index.md'
  - Server Owners:
      - Setting up a Server: 'server-owners/index.md'
  - Developers:
      - Creating new Content: 'developers/index.md'
      - Basics:
        - 'developers/basics/creating-an-addon.md'
        - 'developers/basics/code-style.md'
      - Content Creation:
        - 'developers/content-creation/creating-a-class.md'
        - 'developers/content-creation/creating-a-role.md'
        - 'developers/content-creation/creating-an-item.md'
        - 'developers/content-creation/creating-a-weapon.md'
        - 'developers/content-creation/creating-a-hudelement.md'
        - 'developers/content-creation/creating-a-hud-theme.md'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/TTT-2'
    - type: 'steam'
      link: 'https://steamcommunity.com/sharedfiles/filedetails/?id=1357204556'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
